source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LzmaSDKObjC_Example', :exclusive => true do
  pod "LzmaSDKObjC", :path => "../"
end

target 'LzmaSDKObjC_Tests', :exclusive => true do
  pod "LzmaSDKObjC", :path => "../"

  
end
