use_frameworks!
#platform :ios, '8.0'

target 'LzmaSDK-ObjC' do
  platform :ios, '8.0'
  pod 'Inlineobjc'
end

target 'LzmaSDK-ObjCTests' do
  platform :ios, '8.0'
  pod 'Inlineobjc'
end

target 'LzmaSDK-ObjC-OSX' do
  platform :osx, '10.9'
  pod 'Inlineobjc'
end

target 'LzmaSDK-ObjC-OSXTests' do
  platform :osx, '10.9'
  pod 'Inlineobjc'
end
